### ISSUE TITLE
Incompatible with newer versions of urllib3

### ISSUE THREAD

**Issue by MattShikishima** [jamesnicolas/yomichan-forvo-server#16]
method_whitelist has been removed from urllib3 >=2.0, causing the add-on to crash on startup. Downgrading urllib3 temporarily fixes this issue.

> '⁨Yomichan Forvo Server⁩' 読み込みの際:
⁨Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/addons.py", line 246, in loadAddons
    __import__(addon.dir_name)
  File "/home/matthias/.local/share/Anki2/addons21/580654285/__init__.py", line 190, in <module>
    class ForvoHandler(http.server.SimpleHTTPRequestHandler):
  File "/home/matthias/.local/share/Anki2/addons21/580654285/__init__.py", line 191, in ForvoHandler
    forvo = Forvo(config=_forvo_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthias/.local/share/Anki2/addons21/580654285/__init__.py", line 41, in __init__
    self._set_session()
  File "/home/matthias/.local/share/Anki2/addons21/580654285/__init__.py", line 48, in _set_session
    retry_strategy = Retry(
                     ^^^^^^
TypeError: Retry.__init__() got an unexpected keyword argument 'method_whitelist'
⁩

**Comment by jamesnicolas** [comment]
@MatthiasvZ updated to use `allowed_methods`, let me know if it works for you

**Comment by MattShikishima** [comment]
Yes. It works as expected now.
