### ISSUE TITLE
Failed to load in Anki 2.1.66, MacOS sonoma, MacBook Air 2019, Apple silicon M1

### ISSUE THREAD

**Issue by foxmean** [jamesnicolas/yomichan-forvo-server#19]
Error message below

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.
When loading 'yomichan-forvo-server':
Traceback (most recent call last):|
File "aqtaddons", line 246, in loadAddons
File "/Users/pkmean/Library/Application Support/Anki2/addons21/ yomichan-forvo-server/_init_py", line 138, in <module> class ForvoHandler (http.server.SimpleHTTPRequestHandler):
File "/Users/pkmean/Library/Application Support/Anki2/addons21/ yomichan-forvo-server/_init_py", line 139, in ForvoHandler
forvo = Forvo('zh')
File "/Users/pkmean/Library/Application Support/Anki2/addons21/ yomichan-forvo-server/_init_py", line 26, in _init_
self._set_session ()
File "/Users/pkmean/Library|Application Support/Anki2/addons21/ yomichan-forvo-server/_init_py", line 33, in _set_session
retry_strategy = Retry
TypeError: _init_() got an unexpected keyword argument
'method_whitelist'

**Comment by jamesnicolas** [comment]
@foxmean Do you have the latest version? I don't use `method_whitelist` anymore.

**Comment by foxmean** [comment]
Oh, so sorry I maybe use the version older than [2023-07-28] because the date added file on my system is 2023-01-09. BTW, I cannot update yomichan-forvo-server from 'Check for Update' in Anki Add-on itself. I need to delete it and reinstall (by normal way of install it from code). After that it's work just fine. It is maybe the 'Check for Update' problem of Anki, not your add-on. Thanks for you so much for your contribution to the language learning community.
